In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

In [2]:
data=pd.read_csv(r'C:\Users\kowsar\PycharmProjects\PycharmProjects\pythonProject\venv\Scripts\mother.csv')

In [3]:
h=data.head()
h

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [4]:
data['RiskLevel'].value_counts()

RiskLevel
low risk     406
mid risk     336
high risk    272
Name: count, dtype: int64

In [5]:
data.columns

Index(['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate',
       'RiskLevel'],
      dtype='object')

In [6]:
#converting pandas to numpy becuase sklearn use numpy
x=data[['Age', 'SystolicBP', 'DiastolicBP', 'BS', 'BodyTemp', 'HeartRate',]].values
x

array([[ 25., 130.,  80.,  15.,  98.,  86.],
       [ 35., 140.,  90.,  13.,  98.,  70.],
       [ 29.,  90.,  70.,   8., 100.,  80.],
       ...,
       [ 35.,  85.,  60.,  19.,  98.,  86.],
       [ 43., 120.,  90.,  18.,  98.,  70.],
       [ 32., 120.,  65.,   6., 101.,  76.]])

In [7]:
y=data['RiskLevel'].values
y

array(['high risk', 'high risk', 'high risk', ..., 'high risk',
       'high risk', 'mid risk'], dtype=object)

In [8]:
#normalizing
scaler= preprocessing.StandardScaler()
x_normal=scaler.fit(x).transform(x.astype(float))
print(x_normal)

[[-0.36173812  0.91339632  0.25502279  1.90589019 -0.4852155   1.44695615]
 [ 0.38077697  1.45702716  0.97553854  1.29833966 -0.4852155  -0.53208757]
 [-0.06473208 -1.26112705 -0.46549297 -0.22053665  0.97388449  0.70481475]
 ...
 [ 0.38077697 -1.53294248 -1.18600873  3.12099124 -0.4852155   1.44695615]
 [ 0.97478904  0.36976548  0.97553854  2.81721597 -0.4852155  -0.53208757]
 [ 0.15802244  0.36976548 -0.82575085 -0.82808717  1.70343448  0.21005383]]


In [9]:
#creating train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x_normal, y, test_size=0.2, random_state=4)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(811, 6) (811,)
(203, 6) (203,)


In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
ks=10
for n in range(1,ks):
    neigh1=KNeighborsClassifier(n_neighbors=n).fit(x_train, y_train)
    yhat=neigh1.predict(x_test)
    mean_acc=metrics.accuracy_score(y_test, neigh1.predict(x_test))
    print(mean_acc)

0.8177339901477833
0.7635467980295566
0.6995073891625616
0.6847290640394089
0.6798029556650246
0.6699507389162561
0.6748768472906403
0.6995073891625616
0.6798029556650246


In [11]:
#train model
k=1
neigh=KNeighborsClassifier(n_neighbors=k).fit(x_train, y_train)
neigh

KNeighborsClassifier(n_neighbors=1)

In [12]:
yhat=neigh.predict(x_test)
print(yhat[0:5])
print(y_test[0:5])

['mid risk' 'low risk' 'mid risk' 'high risk' 'low risk']
['mid risk' 'low risk' 'mid risk' 'low risk' 'low risk']


In [13]:
from sklearn import metrics
a1=metrics.accuracy_score(y_train, neigh.predict(x_train))
a2=metrics.accuracy_score(y_test, neigh.predict(x_test))
print(a1)
print(a2)

0.9198520345252774
0.8177339901477833


In [19]:
neigh.predict([[20, 130, 9, 15.0, 8, 86]])

array(['high risk'], dtype=object)